DjangoWeb/Proyectoweb/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('ProyectoWebApp/',include('ProyectoWebApp.urls')), #Aqui se enlaza hacia el urls de otras aplicaciones apps. Ahora las url de la app tendran la forma: http://127.0.0.1:8000/ProyectoWebApp/XXXXXXXX
    path('',include('ProyectoWebApp.urls')),#Si lo hacemos de esta forma, las urls quedaran de la forma normal http://127.0.0.1:8000/XXXXXXX

    path('servicios/', include('servicios.urls')), #registramos la url de nuestra app servicios igual que arriba
    path('contacto/', include('contacto.urls')),
    path('blog/', include('blog.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
]

DjangoWeb/blog/urls.py
#eSTA APP se hizo despues de la prinicpal proyectoweb ver esa primero
from django.urls import path

from . import views



urlpatterns = [

    
    path('', views.blog, name="Blog"),
    path('categoria/<int:categoria_id>/', views.categoria, name="categoria") #Aca creamos una url dinamica que llama al id de losw objetos tipo categoria
    #la logica de dicho URL se encuentra en la funcion categoria de views.py, al poner el url categoria/4/ por ej, le dara el valor 4 a la variable categoria_id
    #lo que servira en views, ver views la funcion categoria para entender
    

]

DjangoWeb/carro/urls.py
#
from django.urls import path

from . import views

app_name="carro" #Esto sirve para evitar confusiones conj otras apps que pudieran tener
# el mismo nombre de paths, entonces si queremos usar el path de agregar podemos poner por ejemplo "carro:agregar"
#ver tienda.html para ver como se usa esto

urlpatterns = [

    #Agregamos las url correpsondientes a las views
    path('agregar/<int:producto_id>/', views.agregar_producto, name="agregar"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name="eliminar"),
    path('restar/<int:producto_id>/', views.restar_producto, name="restar"),
    path('limpiar/', views.limpiar_producto, name="limpiar"),
    

]

DjangoWeb/tienda/urls.py
#eSTA APP se hizo como el nro4
from django.urls import path

from . import views



urlpatterns = [

    
    path('', views.tienda, name="Tienda"),
    

]

DjangoWeb/carro/models.py
from django.db import models

# Create your models here.

DjangoWeb/tienda/models.py
from django.db import models

# Create your models here.

class CategoriaProd(models.Model):
	nombre=models.CharField(max_length=50)
	created=models.DateTimeField(auto_now_add=True)
	updated=models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name="categoriaProd"
		verbose_name_plural="categoriasProd"
	def __str__(self):
		return self.nombre

class Producto(models.Model): #Todo lo de aqui se explico en anteriores apps
	nombre=models.CharField(max_length=50)
	categorias=models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
	imagen=models.ImageField(upload_to="tienda", null=True, blank=True)
	precio=models.FloatField()
	disponibilidad=models.BooleanField(default=True)
	created=models.DateTimeField(auto_now_add=True)
	updated=models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name="Producto"
		verbose_name_plural="Productos"
	def __str__(self):
		return self.nombre

DjangoWeb/carro/views.py
from django.shortcuts import render, redirect

from .carro import Carro #Llamar a carro
from tienda.models import Producto


def agregar_producto(request, producto_id):
	carro=Carro(request)
	producto=Producto.objects.get(id=producto_id)
	carro.agregar(producto=producto)
	return redirect("Tienda")


def eliminar_producto(request, producto_id):
	carro=Carro(request)
	producto=Producto.objects.get(id=producto_id)
	carro.eliminar(producto=producto)
	return redirect("Tienda")

def restar_producto(request, producto_id):
	carro=Carro(request)
	producto=Producto.objects.get(id=producto_id)
	carro.restar_producto(producto=producto)
	return redirect("Tienda")

def limpiar_producto(request, producto_id):
	carro=Carro(request)
	carro.limpiar_carro()
	return redirect("Tienda")

DjangoWeb/tienda/views.py
from django.shortcuts import render

from tienda.models import CategoriaProd, Producto

# Create your views here.

def tienda(request):
	productos=Producto.objects.all()

	return render(request,"tienda/tienda.html", {"productos": productos})
	

DjangoWeb/tienda/templates/carro/widget.html
<table class="table table-bordered" style="color: white">
	<thead> <!--cabecera-->
		<tr>
			<th colspan="3" class="text-center"> <!--Aqui en la cabecera las columnas deberan ser 3 pero combinadas con texto centrado-->
				Carro Compras	

			</th>

		</tr>
		<tr> <!-- Aqui va la segunda fila de la cabecera esta tendra tres columnas -->
			<th>Producto</th>
			<th>Cantidad</th>
			<th>Suma</th>
			
		</tr>

	</thead>
	<tbody>
		<!--Si hay algun elemento en el carro (carro es un diccionario): ... -->
		{% if request.session.carro.items %}
			{% for key, value in request.session.carro.items %} <!-- Recorremos como lo hicimos en carro.py de la app carro notar que en codigo django en tempaltes las funciones se llaman sin (), aqui debe aprecer los productos segun vamos añadiendolos con el boton creado en tienda.html-->
			<tr class="text-center">
				<td>{{value.nombre}}</td> <!--Este value corrersponde a la variable que usa para recorrer los valores del diccionario-->
				<td>{{value.cantidad}}</td>
				<td>
					<a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
					<a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br/>

					{{value.precio}} S/.



				</td>
			</tr>

			{% endfor %}

		{%else%} <!--En caso no haya nada en el carro saldra una advertencia... -->
			<tr>
				<td colspan="3">
					<div class="alert alert-danger text-center">
						Sin Productos!!							

					</div>
				</td>

			</tr>

		{% endif%}
	</tbody>

	<tfoot>
		<tr >
			<td colspan="3">
			
				Total: {{importe_total_carro}}
			</td>
			
			
		</tr>

	</tfoot>

</table>